#ifndef __EVENT_MSG_DEF_H__
#define __EVENT_MSG_DEF_H__

typedef enum {
	TUI_EVENT_PRESSED		= 0,
	TUI_EVENT_PRESSING		= 1,
	TUI_EVENT_PRESS_LOST		= 2,
	TUI_EVENT_SHORT_CLICKED		= 3,
	TUI_EVENT_LONG_PRESSED		= 4,
	TUI_EVENT_LONG_PRESSED_REPEAT	= 5,
	TUI_EVENT_CLICKED		= 6,
	TUI_EVENT_RELEASED		= 7,
	TUI_EVENT_DRAG_BEGIN		= 8,
	TUI_EVENT_DRAG_END		= 9,
	TUI_EVENT_DRAG_THROW_BEGIN	= 10,
	TUI_EVENT_GESTURE		= 11,
	TUI_EVENT_KEY			= 12,
	TUI_EVENT_FOCUSED		= 13,
	TUI_EVENT_DEFOCUSED		= 14,
	TUI_EVENT_LEAVE			= 15,
	TUI_EVENT_VALUE_CHANGED		= 16,
	TUI_EVENT_INSERT		= 17,
	TUI_EVENT_REFRESH		= 18,
	TUI_EVENT_APPLY			= 19,
	TUI_EVENT_CANCEL		= 20,
	TUI_EVENT_DELETE		= 21,
	TUI_EVENT_LAST			= 22,












	TUI_EVENT_USER_DEF = 0x1000,
	TUI_EVENT_OBJECT_INIT,
	TUI_EVENT_SOUND_PLAY_END,
	TUI_EVENT_IMAGE_ANIMATION_END,
}tui_event_e;

#endif /* __EVENT_MSG_DEF_H__ */
