#ifndef __SYS_MSG_DEF_H__
#define __SYS_MSG_DEF_H__

typedef enum {
	TUI_SYS_MSG_VIEW_CREATE = 0x1000,











	TUI_USER_MSG_DEF_OK = 0x2000,
	TUI_USER_MSG_DEF_CANCEL,
	TUI_USER_MSG_EXAMPLES_CREATE,
	TUI_USER_MSG_EXAMPLES_DEMO,

	TUI_USER_MSG_APP_LOGO,
	TUI_USER_MSG_APP_LOGIN_CHECK,
	TUI_USER_MSG_APP_LOGIN_OK,
	TUI_USER_MSG_APP_POWER_DOWN,
	TUI_USER_MSG_APP_BACK,
	TUI_USER_MSG_APP_HOME,
	TUI_USER_MSG_APP_ENTER_HOME,
	TUI_USER_MSG_HOME_SCREEN_SWITCH,
	TUI_USER_MSG_APP0,
	TUI_USER_MSG_APP1,
	TUI_USER_MSG_APP1_BTN1,
	TUI_USER_MSG_APP1_BTN2,
	TUI_USER_MSG_APP1_BTN3,
	TUI_USER_MSG_APP1_BTN_IMG1,
	TUI_USER_MSG_APP1_BTN_IMG2,
	TUI_USER_MSG_APP1_SWITCH,
	TUI_USER_MSG_APP2,
	TUI_USER_MSG_APP2_BTN1,
	TUI_USER_MSG_APP2_BTN2,
	TUI_USER_MSG_APP2_BTN_UP,
	TUI_USER_MSG_APP2_BTN_DOWN,
	TUI_USER_MSG_APP3,
	TUI_USER_MSG_APP3_BAR1,
	TUI_USER_MSG_APP3_BAR2,
	TUI_USER_MSG_APP4,
	TUI_USER_MSG_APP4_START,
	TUI_USER_MSG_APP4_BTN,
	TUI_USER_MSG_APP5,
	TUI_USER_MSG_APP5_ANGLE,
	TUI_USER_MSG_APP6,
	TUI_USER_MSG_APP6_WIND1,
	TUI_USER_MSG_APP6_WIND1_YES,
	TUI_USER_MSG_APP6_WIND1_NO,
	TUI_USER_MSG_APP6_WIND2,
	TUI_USER_MSG_APP6_WIND2_YES,
	TUI_USER_MSG_APP6_WIND3,
	TUI_USER_MSG_APP6_WIND4,
	TUI_USER_MSG_APP7,
	TUI_USER_MSG_APP7_SOUND1,
	TUI_USER_MSG_APP7_SOUND2,
	TUI_USER_MSG_APP7_SOUND3,
	TUI_USER_MSG_APP7_SOUND4,
	TUI_USER_MSG_APP8,
	TUI_USER_MSG_APP9,
	TUI_USER_MSG_APP9_CLICK,
	TUI_USER_MSG_APP9_CLICK_PRESSED,
	TUI_USER_MSG_APP9_CLICK_RELEASED,
	TUI_USER_MSG_APP10,
	TUI_USER_MSG_APP10_LANG,
	TUI_USER_MSG_APP10_FS,
	TUI_USER_MSG_APP10_FS_BACK,
	TUI_USER_MSG_APP11,
	TUI_USER_MSG_APP11_SUBMIT,

	TUI_USER_MSG_MAX,
} tui_sys_msg_def_e;

#endif /* __SYS_MSG_DEF_H__ */
